
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMASMENOSleftPORENTREABRE_RPN BOOLEANO CADENA CADENA_VALOR CIERRA_RPN CIERTO COMA CUANDO DIFIERE ENTERO ENTONCES ENTRE EQUIVALE FALSO FIN IDENTIF IDENTIF_ILEGAL IGUAL IMPRIMIR INICIO LEER LISTO MAS MAYORQUE MAYOR_IGUAL MENORQUE MENOR_IGUAL MENOS MIENTRAS NO NUMERO O PARDE PARIZ POR PUNTO REAL SINO Y number variableexpression   : expression MAS expression\n                    | expression MENOS expression\n                    | expression POR expression\n                    | expression ENTRE expression\n                    | PARIZ expression PARDE\n                    | ABRE_RPN special_expression CIERRA_RPN\n                    | variable\n                    | numberspecial_expression   : special_expression special_expression MAS\n                            | special_expression special_expression MENOS\n                            | special_expression special_expression POR\n                            | special_expression special_expression ENTRE\n                            | variable\n                            | number'
    
_lr_action_items = {'PARIZ':([0,2,6,7,8,9,],[2,2,2,2,2,2,]),'ABRE_RPN':([0,2,6,7,8,9,],[3,3,3,3,3,3,]),'variable':([0,2,3,6,7,8,9,11,12,13,19,21,22,23,24,],[4,4,12,4,4,4,4,12,-13,-14,12,-9,-10,-11,-12,]),'number':([0,2,3,6,7,8,9,11,12,13,19,21,22,23,24,],[5,5,13,5,5,5,5,13,-13,-14,13,-9,-10,-11,-12,]),'$end':([1,4,5,14,15,16,17,18,20,],[0,-7,-8,-1,-2,-3,-4,-5,-6,]),'MAS':([1,4,5,10,12,13,14,15,16,17,18,19,20,21,22,23,24,],[6,-7,-8,6,-13,-14,-1,-2,-3,-4,-5,21,-6,-9,-10,-11,-12,]),'MENOS':([1,4,5,10,12,13,14,15,16,17,18,19,20,21,22,23,24,],[7,-7,-8,7,-13,-14,-1,-2,-3,-4,-5,22,-6,-9,-10,-11,-12,]),'POR':([1,4,5,10,12,13,14,15,16,17,18,19,20,21,22,23,24,],[8,-7,-8,8,-13,-14,8,8,-3,-4,-5,23,-6,-9,-10,-11,-12,]),'ENTRE':([1,4,5,10,12,13,14,15,16,17,18,19,20,21,22,23,24,],[9,-7,-8,9,-13,-14,9,9,-3,-4,-5,24,-6,-9,-10,-11,-12,]),'PARDE':([4,5,10,14,15,16,17,18,20,],[-7,-8,18,-1,-2,-3,-4,-5,-6,]),'CIERRA_RPN':([11,12,13,21,22,23,24,],[20,-13,-14,-9,-10,-11,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,6,7,8,9,],[1,10,14,15,16,17,]),'special_expression':([3,11,19,],[11,19,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression MAS expression','expression',3,'p_expression','parser0_eng.py',12),
  ('expression -> expression MENOS expression','expression',3,'p_expression','parser0_eng.py',13),
  ('expression -> expression POR expression','expression',3,'p_expression','parser0_eng.py',14),
  ('expression -> expression ENTRE expression','expression',3,'p_expression','parser0_eng.py',15),
  ('expression -> PARIZ expression PARDE','expression',3,'p_expression','parser0_eng.py',16),
  ('expression -> ABRE_RPN special_expression CIERRA_RPN','expression',3,'p_expression','parser0_eng.py',17),
  ('expression -> variable','expression',1,'p_expression','parser0_eng.py',18),
  ('expression -> number','expression',1,'p_expression','parser0_eng.py',19),
  ('special_expression -> special_expression special_expression MAS','special_expression',3,'p_special_expression','parser0_eng.py',25),
  ('special_expression -> special_expression special_expression MENOS','special_expression',3,'p_special_expression','parser0_eng.py',26),
  ('special_expression -> special_expression special_expression POR','special_expression',3,'p_special_expression','parser0_eng.py',27),
  ('special_expression -> special_expression special_expression ENTRE','special_expression',3,'p_special_expression','parser0_eng.py',28),
  ('special_expression -> variable','special_expression',1,'p_special_expression','parser0_eng.py',29),
  ('special_expression -> number','special_expression',1,'p_special_expression','parser0_eng.py',30),
]
